#!/bin/bash

# Toggles alsamixer master mute.

CUR_SINK="`pacmd list-sink-inputs | grep 'sink:' | head -1 | awk '{ print $2; }'`"
CUR_MUTE="`amixer get Master | \
	sed -e '/\[.*\]/!d' -e 's/.*\[\([onf]*\)\].*/\1/' | \
	head -1`"

[[ "$CUR_MUTE" == "on" ]] && NEW_MUTE="off" || NEW_MUTE="on"

amixer set Master "$NEW_MUTE" &> /dev/null
pacmd set-sink-mute "$CUR_SINK" "$CUR_MUTE"

