#!/bin/bash

trap "exit 0;" SIGINT SIGTERM SIGHUP


WORK=25
BREAK=5

# "d" stands for default (time).
[ -n $1 -a "$1" != "d" ] && WORK=$1
[ -n $2 -a "$2" != "d" ] && BREAK=$2

clear
pause -r "Press any key to start BPT ... "

for ((i=0;;i++)); do
	countdown -i -o "00:`printf '%02d' $WORK`:00" \
		-n "BPT Work (${i})"
	countdown -i -o "00:`printf '%02d' $BREAK`:00" \
		-n "BPT Break (${i})"
done

