#!/bin/bash

trap "exit 0;" SIGINT SIGTERM SIGHUP

clear
pause -r "Press any key to start BPT ... "

for ((i=0;;i++)); do
	TIME=15;
	countdown -i -o "00:`printf '%02d' $TIME`:00" \
		-n "BPT Work (${i})"
	TIME=3;
	countdown -i -o "00:`printf '%02d' $TIME`:00" \
		-n "BPT Break (${i})"
done

