#!/bin/bash

#  bpt.sh
#  Code
#
#  Created by Alex Striff on 2014-02-16.
#  Uncopyrighted.
#


POM=0
WORK=900 # 15 minutes.
BREAK=300 # 5 minutes.

SOUND="/Users/alexstriff/Library/Sounds/Pomodoro.aif"


# Display countdown.
function countdown() {

    TYPE=""
    TIME=0
    ALERT=false

    if [[ $[$POM % 2] == 1 ]]; then
        TYPE="Work"
        TIME=$WORK
        COUNT=$[$POM/2]

    else
        TYPE="Break"
        TIME=$BREAK
    fi

    for (( i = $TIME; i >= 0; i-- )); do

        MINUTES=$[$i/60]
        SECONDS=$[$i%60]

        printf "\t[%02d]\t\t[%02d:%02d]\t\t[%s]\r"\
            $COUNT $MINUTES $SECONDS $TYPE
        sleep 1

    done

}

# Visual alert and audio plays.
function play_sound() {

    echo 
    afplay $SOUND

}

# Launch messages.
function print_info() {

    echo "Running 'bpt.sh':"
echo "->->->->->->->->->->->->->->->->->->->->->->->->->->->"

printf "\tWORK:\t\t%03d seconds\t(%02d minutes).\n"\
    $WORK $[$WORK/60]
printf "\tBREAK:\t\t%03d seconds\t(%02d minutes).\n"\
    $BREAK $[$BREAK/60]

echo "->->->->->->->->->->->->->->->->->->->->->->->->->->->"
echo -e "\tPomodoros:\tTime Left:\tTimer:"

}


clear
pause -r
print_info

for (( POM=1; POM>-1; POM++ )); do

    countdown
    play_sound

done

