#!/bin/bash

if [[ "$1" == "-q" ]]; then

    echo -en "\033[0;32m" # colored question
    read -p "> CD to PROJECT_FOLDER? " ANS
    echo -en "\033[0m"

    if [[ "$ANS" == 'y' ]]; then
        cd "$PROJECT_FOLDER"
    else
        cd
    fi

    echo # newline.

elif [[ "$1" == "-c" ]]; then
    cd "$CODE"

elif [[ "$1" == "-l" ]]; then
    cdl "$PROJECT_FOLDER"

elif [[ "$1" == "-cl" ]]; then
    cdl "$CODE"

else
    cd "$PROJECT_FOLDER"
fi

