#!/bin/bash

touch ~jfjhh/.owncloud_dirmail/{dirmail_tmp,email,change}.txt

while :; do
	echo "cat ~jfjhh/.owncloud_dirmail/change.txt" | \
		~jfjhh/bin/ifchanged -c stdin -i 5
	mutt -s "Your OwnCloud directory has changed." \
		`cat ~jfjhh/.owncloud_dirmail/email.txt` < \
		~jfjhh/.owncloud_dirmail/dirmail_tmp.txt
done

