#!/bin/bash

function print_help()
{
	[ -n "$1" ] && echo "ERROR: $1"
	cat <<-EOF
	USAGE: dirmail {-h} [-e EMAIL] [-d PATH] {-f LSFLAGS (default -Flh)}
	EOF
	exit -1
}

CHANGES=0
[[ -z $TMPDIR ]] && TMP="/tmp" || TMP=$TMPDIR
TMPFILE="`mktemp $TMP/dirmail_tmp.XXXX`"

function quit()
{
	echo "Cleaning up ... (removing tempfile $1)."
	rm "$1"
	echo "Exiting."
	exit 1;
}

trap "quit $TMPFILE;" SIGINT SIGTERM

function main()
{
	DIR=""
	EMAIL=""
	ADMIN_EMAIL="alex.striff1@gmail.com"
	LSFLAGS="-Flh"
	CMDSTR=""
	KEY="/home/pi/.ssh/dirmail_rsa"

	[ $# -lt 2 ] && print_help "Only got $# arg(s)."


	while getopts "hd:e:" ARG; do
		case $ARG in
			'd' )
				DIR="$OPTARG"
				;;
			'e' )
				EMAIL="$OPTARG"
				;;
			'f' )
				LSFLAGS="$OPTARG"
				;;
			'h' )
				print_help
				;;
		esac
	done

	[ -z "$DIR" ] && print_help "Bad dir value: $DIR"
	[ -z "$EMAIL" ] && print_help "Bad email value: $EMAIL"
	[ -z "$LSFLAGS" ] && print_help "Bad ls flags: $LSFLAGS"

	CMDSTR="find $DIR -exec ls $LSFLAGS {} \\\; \| grep -v --color=never \
		'ownCloud/\.[a-z0-9]*'"
	echo -e "emailing output when changed of:\n$CMDSTR\n... to <$EMAIL>."

	while :; do
		echo -en "\tChange messages sent: $CHANGES.\r"
		cat <<-EOF > "$TMPFILE"

		*ATTENTION: Your OwnCloud directory (at $DIR) has changed! The difference
		is documented below:

		================================

		EOF
		echo "$CMDSTR" | /home/pi/bin/ifchanged -c stdin -i 2 -sd >> $TMPFILE
		[ $? -eq 2 ] && quit $TMPFILE
		cat <<-EOF >> "$TMPFILE"

		================================

		* If you no longer wish to recieve automated messages, or want to only
		monitor a specific directory, contact the admin at <${ADMIN_EMAIL}>.

		This automated message was sent on `date`.

		EOF

		scp -i "$KEY" "$TMPFILE" \
			"jfjhh@debian.local:~/.owncloud_dirmail/dirmail_tmp.txt"
		echo "$EMAIL" > "$TMPFILE"
		scp -i "$KEY" "$TMPFILE" \
			"jfjhh@debian.local:~/.owncloud_dirmail/email.txt"
		echo "$RANDOM" > "$TMPFILE"
		scp -i "$KEY" "$TMPFILE" \
			"jfjhh@debian.local:~/.owncloud_dirmail/change.txt"
		let CHANGES=$[$CHANGES + 1]

		rm "$TMPFILE"
	done
}

( main $* )

