#!/bin/bash

df -H | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $5 " " $1 }' |
while read output; do

    echo $output
    usep=`echo $output | awk '{ print $1}' | cut -d'%' -f1`
    partition=`echo $output | awk '{ print $2 }'`

    if [ $usep -ge 90 ]; then
        echo "Running out of disk space \"$partition ($usep%)\" on `hostname` as on `date`" |
        mail -s "Alert: Almost out of disk space $usep%" pi

    elif [ $usep -ge 50 ]; then
        echo "Using a lot of disk space \"$partition ($usep%)\" on `hostname` as on `date`" |
        mail -s "Alert: Half or more of disk space $usep%" pi
    fi

done

