#!/bin/bash
# egit
# commits a file with a message, like a git add-commit 'file' 'message'.

if [ -d ".git" ]; then
    echo "EXPLICIT-COMMIT '$1'."
    git add "$1"
    git commit -m "$2"
else
    echo "NOT A GIT REPOSITORY."
fi

