#!/bin/bash
#
# grep_delete
# Deletes all lines with any of the strings in $2 from the file $1.
#
# For example:
# `grep_delete delfile.txt 'del1|del2|del3'`
#
# $1 is filename.
# $2 is regex string(s).
#

if [[ $# -eq 2 ]]; then

    grep -Ev $2 $1 > tmp.txt
    cat tmp.txt > $1
    rm tmp.txt

else

    echo -e "\033[0;92mUseage: grep_delete <file> 'regex|strings'"

fi

