#!/bin/bash

note_file="$HOME/.notes.txt"
note_bak="$HOME/.notes.txt.bak"
pager="cat -n"

date_stamp="`date +'[%F %R]%t'`"

modes="h l a d u" # help, list, add, delete, undo
mode_ok=false
[ $# -eq 0 ] && mode="l" || mode="$1"
for m in $modes; do
	[[ "$m" == "$mode" ]] && mode_ok=true && break
done
$mode_ok || mode="h"
shift

if [[ "$mode" == "l" ]]; then
	$pager $note_file
elif [[ "$mode" == "a" ]]; then
	cp $note_file $note_bak
	echo "${date_stamp}$*" >> $note_file
elif [[ "$mode" == "d" ]]; then
	cp $note_file $note_bak
	ed -s $note_file <<-EOF
	$1
	d
	wq
	EOF
elif [[ "$mode" == "u" ]]; then
	cp $note_bak $note_file
	$pager $note_file
else
	cat <<-EOF
	======= This is note v0.0.1. =======
	Help	note h
	List	note [l]
	Add	note a things [...]
	Delete	note d things [...]
	Undo	note u
	====================================
	Using note file:
	$note_file
	====================================
	EOF
fi

