#!/bin/bash

SAVED_TTY=$(stty -g)

function p_fun()
{
	echo -n "$MESSAGE"
	stty raw
	dd if="/dev/tty" of="/dev/null" count="1" 2> /dev/null
	stty "$SAVED_TTY"
}

ARG="$1"
shift
[ -n "$*" ] && MESSAGE="$*" || MESSAGE="Press any key to continue ... "

if [[ "$ARG" == "-r" ]]; then
	p_fun
	echo -ne "\r                                     \r" # Clears the message.
else
	p_fun
	echo # Newline.
fi

