#!/bin/bash
# ~/bash/push_repos
# does a git push of all git repos

RUN_DIR=`pwd`
REPOS="/home/pi/bash /home/pi/c/sudoku_solver /home/pi/c/approx_pi /home/pi/c/lcthw /home/pi/dotfiles /home/pi/css"

printf " \033[0;34m<push_repos> \033[0;1;32mRunning push_repos with repos: \033[0;1;37m$REPOS\033[0m...\n"

for REPO in $REPOS; do
    printf " \033[0;34m<push_repos> \033[0;1mCDing to \033[0;1;36m$REPO\033[0m...\r"
    cd $REPO

    printf " \033[0;34m<push_repos> \033[0;1mShort status of \033[0;1;36m$REPO\033[0m:\n"
    git status -s

    printf " \033[0;34m<push_repos> \033[0;1mPushing \033[0;1;36m$REPO\033[0m...\r"
    git push origin master
    printf " \033[0;34m<push_repos> \033[0;1mDone pushing \033[0;1;36m$REPO\033[0m.\n"
done

printf "\n"
printf " \033[0;34m<push_repos> \033[0;1;32mDONE running push_repos\033[0m...\n"

cd $RUN_DIR

