#!/bin/bash
#
# qgit
# Easy committing from Vim.
#
# Takes $1 that is the filename.
# Takes $2 that is the commit message.
#
# Runs `git' commands silently.
#

COMMIT_MESSAGE=""
TARGET_DIR=`dirname $1`
RUN_DIR=`pwd`

# Go to the directory of the file.
cd $TARGET_DIR

if [[ "$2" == "" ]]; then
    COMMIT_MESSAGE="Wrote $1 (`date "+%m-%d-%y/%T"`)."
else
    COMMIT_MESSAGE="$2"
fi

# Make silent by redirecting STDOUT and STDERR to /dev/null with `&>'.
git add "$1" &> /dev/null
git commit -m "$COMMIT_MESSAGE" &> /dev/null

if [[ $? == 0 ]]; then
    echo "AUTO-COMMITTED '$1' with commit message '$COMMIT_MESSAGE'."

else
    echo "NOT A GIT REPOSITORY. - '$1'"
fi

# Go back to run directory.
cd $RUN_DIR

