#!/bin/bash
# Takes the number of minutes to lock the screen.
# After the time specified has passed, you can move the mouse or type on
# the keyboard to use the system.

function usage()
{
	echo "USAGE: screeenlock <minutes>"
	echo "Please enter a valid time to lock."
	return 1
}

# Test for an X-session.
if [[ -z "$DISPLAY" ]]; then
	echo "Must be in an X-session to run."
	return 2
fi

# Test the argument is a valid number ( 0 > $1 > 500 ).
RE='^[0-9]+$'

if ! [[ $1 =~ $RE ]]; then
	usage

elif [ $1 -gt 500 ]; then
	usage

else
	# Log locking time to the console.
	echo "Locking for $1 minutes..."

	# Input devices list (approximation).
	ID_LIST=""
	for ID in {2..15}; do
		ID_LIST+="$ID "
	done

	#  Disable input devices.
	echo "Disabling input devices...$ID_LIST"
	for DEVICE_ID in $ID_LIST; do
		xinput set-prop $DEVICE_ID "Device Enabled" 0 2> /dev/null
		printf "\t%2d down\n" $DEVICE_ID
	done

	# Activate screensaver.
	xscreensaver-command -activate

	# Wait until reactivation of input devices is allowed (calculate
	# seconds because you can't do $VARm like you could do 1m for 1 minute).
	echo "Sleeping..."
	sleep $[ $1 * 60 ]

	# Enable input devices.
	echo "Enabling input devices..."
	for DEVICE_ID in $ID_LIST; do
		xinput set-prop $DEVICE_ID "Device Enabled" 1 2> /dev/null
		printf "\t%2d up\n" $DEVICE_ID
	done
fi

