#!/bin/bash

SINKS="`pacmd list-sinks | grep 'index:' | sed 's/*//' | awk '{ print $2; }'`"
CUR_SINK="`pacmd list-sink-inputs | grep 'sink:' | head -1 | awk '{ print $2; }'`"

for s in $SINKS; do
	[[ "$s" -ne "$CUR_SINK" ]] && SINK="$s"
done

INPUTS="`pacmd list-sink-inputs | grep 'index:' | awk '{ print $2; }'`"
for i in $INPUTS; do
	pacmd move-sink-input $i $SINK
done

